document.querySelector("li a").style.color="red";
document.querySelector("h1").style.color="pink";
document.querySelector("li a").fontsize="30px";
document.querySelector("button").style.backgroundColor="yellow";
document.querySelector("ul").style.color="blue";
document.querySelector("button").classList.add("invisible");
document.querySelector("button").classList.remove("invisible");
document.querySelector("button").style.backgroundColor="yellow";
document.querySelector("button").classList.remove("invisible");
document.querySelector("h1").classList.add("huge");